### ISSUE TITLE
Optional file validation

### ISSUE THREAD

**Issue by daneren2005** [wgenial/s3-objects-stream-zip-php#1]
In my case where I was trying to zip up thousands of photos at once, the file validation was making it take 2-3 minutes before the zip actually started streaming.  While I get the value of making sure all of the files exist before doing this, I think it makes sense to have an option to silently skip those files during streaming instead of trying to validate them all up front.

**Comment by giovanigenerali** [comment]
@daneren2005 I'm going to take a look at this, thanks!

**Comment by giovanigenerali** [comment]
@daneren2005 take a look at v2.0.0, now you can set to skip validation of the object.

**Comment by daneren2005** [comment]
Sweet that works great.  Thank you for the fast fix for this!
