### ISSUE TITLE
Which IAM policy?

### ISSUE THREAD

**Issue by wrabit** [wgenial/s3-objects-stream-zip-php#4]
Do you happen to know which IAM policy is needed to permit the fopen in this library?

![image](https://user-images.githubusercontent.com/5918271/58026277-65449080-7b16-11e9-8023-684adcde1810.png)

**Comment by wrabit** [comment]
Actually, none changed it. I came here because I am getting 

```"Bucket `xxx` does not exists and/or you have not permission to access it."```

(it was working before a recent overhaul in our IAM users and policies)

**Comment by giovanigenerali** [comment]
@wrabit according to the documentation it is necessary ```ListBucket``` and ```GetObject```

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

> **Note**
> The stream wrapper is designed for working with objects and buckets on which you have at least read permission. This means that your user should have permission to execute **ListBucket** on any buckets and **GetObject** on any object with which the user needs to interact. For use cases where you don't have this permission level, we recommended that you use S3 client operations directly.

**Comment by wrabit** [comment]
That fixed it, thanks.
