### ISSUE TITLE
is it Possible to download a particular Folder?

### ISSUE THREAD

**Issue by NirajVisana** [wgenial/s3-objects-stream-zip-php#5]
Can I Only pass folder name and get a zip of that particular folder?  I tried Using Iterator But it isn't working.

**Comment by giovanigenerali** [comment]
@nirajspitze9 no, it only works to zip objects but you can take a look at this https://github.com/jmathai/s3-bucket-stream-zip-php

**Comment by NirajVisana** [comment]
will it work with version 3 aws php sdk?

**Comment by giovanigenerali** [comment]
@nirajspitze9 I don't know if it works using v3.
