### ISSUE TITLE
Corrupted Zip

### ISSUE THREAD

**Issue by luxaloli** [wgenial/s3-objects-stream-zip-php#6]
Hello, 

I used your implementation for downloading S3 files through PHP like this

`<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
  include __DIR__.'/../vendor/autoload.php';

  use Aws\S3\Exception\S3Exception;
  use WGenial\S3ObjectsStreamZip\S3ObjectsStreamZip;
  use WGenial\S3ObjectsStreamZip\Exception\InvalidParamsException;

  try {

    header('Content-Description: File Transfer');
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="imagenes.zip"');
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    $zipStream = new S3ObjectsStreamZip(array(
      'version' => 'latest', 
      'region' => 'us-west-2', 
      'credentials' => array(
        'key'    => 'key',
        'secret' => 'secret'
      )
    ));
    $objectsA = array();
    $files = json_decode($_POST['fileData']);
    foreach ($files as $file) {
      //array_push($objectsA, $file);
      array_push($objectsA, array(
        'path' => 'asseetFiles/'.$file->file,
        'name' => 'asseetFiles/'.$file->name
      ));
    }
    $bucket = 'kaab-files'; // required
  

    $zipname = 'imagenes.zip'; // required

    $checkObjectExist = false; // no required | default = false

    $zipStream->zipObjects($bucket, $objectsA, $zipname, $checkObjectExist);

  }
  catch (InvalidParamsException $e) {
    echo $e->getMessage();
  }
  catch (S3Exception $e) {
    echo $e->getMessage();
  }
`
 and some times  the result file is corrupted, not all files are included,

You have any idea how can i fix that?

**Comment by giovanigenerali** [comment]
@luxaloli take a look if there are files with the same name. Try renaming by doing some increment ```file (1).jpg``` before zip, maybe that's the problem.

**Comment by luxaloli** [comment]
@giovanigenerali I made that change and i've got a small improvement, but not complerely solved the problem.

I am trying on this example to download 2065 files and only got about 1200 and some are corrupted.

Another way that can be done?

**Comment by giovanigenerali** [comment]
@luxaloli you can try this version using ```GuzzleHttp``` https://github.com/sjoerdstaal/s3-objects-stream-zip-php/blob/master/src/S3ObjectsStreamZip.php 
There is a pull request #3 opened here but I couldn't test if it works correctly.

I don't know if the files are in the same bucket or folder, but you can try this library if it's your case https://github.com/jmathai/s3-bucket-stream-zip-php

**Comment by luxaloli** [comment]
@giovanigenerali That totally fix it, thank you

**Comment by giovanigenerali** [comment]
@luxaloli using GuzzleHttp fixed?

**Comment by luxaloli** [comment]
@giovanigenerali Yes, on that 2065 file example without GuzzleHttp only downloaded about a third of them with a corrupt zip file ant with GuzzleHttp it downloaded all of them without problem.

**Comment by giovanigenerali** [comment]
@luxaloli that's nice. I will take a look on this PR #3 and accept as soon as possible. Thank you for your feedback.

**Comment by giovanigenerali** [comment]
reopened to be fixed  PR #3
