### ISSUE TITLE
Connection With S3 using IAm role

### ISSUE THREAD

**Issue by yasirdev1** [wgenial/s3-objects-stream-zip-php#8]
how can i get connection with S3 using IAM role? as in IAM role credentials are not passed while connection make. but in this case credentials is required to make connection with S3.

**Comment by giovanigenerali** [comment]
@yasirdev1 is not possible with this library. 

There is an article about IAM x S3 https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/

Feel free to make adjustments to this library if you can make this kind of connection.
